#esconde a trace de erro
#server:
#  error:
#    include-binding-errors: never
#  servlet:
#   context-path: /api
 
spring:    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true


      
#security:
#    oauth2:
#      client:
#        scope: password
#        client-id: employeer
#        client-secret: 123
